#!/usr/bin/env bash

version="1.1.4"

export SKIM_DEFAULT_OPTIONS="--ansi --multi --tiebreak=length --inline-info \
--preview-window=right:60%:wrap --nth 1 --bind 'tab:toggle' --color=pointer:white"

skim_preview() {
    printf "paru --color=always %s {1} | " "$1"
    printf "awk '{ sub(/ *:/,\":\"); \$1 = \$1; print }'\n"
}

install() {
    read -ra cmd <<< "$2"

    error_msg=$(mktemp)
    paru -Sl --color=always 2> "$error_msg" |\
    awk '{if (NF > 3) {$4 = "\033[1;33m* ";} print $2, $4 $1;}' |\
    sk --prompt="$1:" --preview "$(skim_preview -Si)" |\
    awk '{print $NF "/" $1}' |\
    xargs -ro "${cmd[@]}"
    [ -s "$error_msg" ] &&\
    cat "$error_msg" &&\
    printf "\033[1mError:\033[0m Paru is not functioning properly. Please check your connection.\n" >&2
    rm -f "$error_msg"
}

query() {
    paru $2 --color=always |\
    sk --prompt="$1:" --preview "$(skim_preview -Qi)" |\
    awk '{print $1}' |\
    xargs -ro $3
}

upgrade() {
    paru -Sy 2> /dev/null
    [ $? -ne 0 ] &&\
    printf "\033[1mError:\033[0m Updating the package databases failed.\n" >&2
    printf "\033[1m:: Checking for upgradable packages...\033[0m\n"
    pkgs=$(paru -Qu --color=always 2> /dev/null)
    pkgs_count=$(wc -l <<< "$pkgs")
    [ -z "$pkgs" ] &&\
    printf " there is no upgradable package\n" && exit 0
    printf " listed %d package%s\n" "$pkgs_count" "$( [ "$pkgs_count" -eq 1 ] || printf s )"
    sk --prompt="u:" --preview "$(skim_preview -Si)" <<< $pkgs |\
    awk '{print $1}' |\
    xargs -ro paru -S --needed
}

help() {
    prog=$(basename "$0")
    cat << EOF
Info:
    $prog v$version
    A package search TUI for Paru, powered by Skim.
    It can install, upgrade, remove, and query packages.

Usage:
    $prog       -> Default action
    $prog [opt] -> Other options

    The default action is to search for and install packages.
    A '*' indicates that the package is already installed.

Multiple Selection:
    Tab         -> Select / Deselect
    Ctrl + i    -> Select / Deselect

Options:
    h -> Print this message
    p -> Print only; do not install
    u -> Upgrade upgradable packages
    r -> Remove installed packages
    R -> Remove explicitly installed packages
    q -> Show installed packages
    Q -> Show explicitly installed packages
EOF
}

invalid_option() {
    printf "\033[1mError:\033[0m Invalid option. " >&2
    printf "Use \"%s --help\" for more information.\n" "$(basename "$0")" >&2
    exit 2
}

[ -n "$2" ] && invalid_option
case $1 in
    "") install ":" "paru -S";;
    -p | p) install "p";;
    -u | u) upgrade;;
    -r | r) query "r" "-Q" "paru -R";;
    -R | R) query "R" "-Qe" "paru -R";;
    -q | q) query "q" "-Q";;
    -Q | Q) query "Q" "-Qe";;
    -h | h | --help) help;; *) invalid_option;;
esac
